//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlGastos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public string Comercio { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdFondoMonetario { get; set; }
        public int IdCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
