//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlGastos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deposito> Depositoes { get; set; }
        public virtual DbSet<FondosMonetario> FondosMonetarios { get; set; }
        public virtual DbSet<Gasto> Gastos { get; set; }
        public virtual DbSet<GastosDetalle> GastosDetalles { get; set; }
        public virtual DbSet<Presupuesto> Presupuestoes { get; set; }
        public virtual DbSet<TipoDocumentoGasto> TipoDocumentoGastoes { get; set; }
        public virtual DbSet<TipoFondosMonetario> TipoFondosMonetarios { get; set; }
        public virtual DbSet<TiposGasto> TiposGastoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
